# Generated by Django 5.1.4 on 2024-12-06 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='email',
        ),
        migrations.AddField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(default='6546846846438', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
