# Generated by Django 5.1.4 on 2024-12-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_verification_email_verification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
