# Generated by Django 5.1.4 on 2024-12-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_verification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='verification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
